name: 'Build Nativelink'

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          repository: TraceMachina/nativelink
          ref: v0.3.0
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          TOOLCHAIN_VERSION: 1.77
          UPLOAD_MODE: none
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}