name: 'Build Nativelink'

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          repository: TraceMachina/nativelink
          ref: v0.4.0
      - name: Patch nativelink
        run: echo $(pwd)
        shell: bash
      - uses: actions/checkout@master
      - name: Patch nativelink
        run: echo $(pwd)
        shell: bash
      - name: Patch nativelink
        run: git apply ../bazel-remote/nativelink-patch/nativelink_v_0_4_0.patch
        shell: bash
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          TOOLCHAIN_VERSION: 1.77
          UPLOAD_MODE: none
          ARCHIVE_TYPES: tar.gz
          ARCHIVE_NAME: nativelink
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
